import type { IconType } from "react-icons";
import {
  MdAccountBalance,
  MdAllInclusive,
  MdAutoStories,
  MdBed,
  MdCheckroom,
  MdCleanHands,
  MdDarkMode,
  MdDirectionsCar,
  MdDining,
  MdDiversity1,
  MdExitToApp,
  MdFace,
  MdFilter3,
  MdFlightTakeoff,
  MdHealthAndSafety,
  MdHome,
  MdLightMode,
  MdLocalDrink,
  MdMeetingRoom,
  MdMenuBook,
  MdRestaurant,
  MdSentimentDissatisfied,
  MdSetMeal,
  MdSick,
  MdSingleBed,
  MdSpa,
  MdSupport,
  MdThunderstorm,
  MdVolunteerActivism,
  MdWaterDrop,
  MdWbSunny,
  MdWbTwilight,
} from "react-icons/md";

const occasionIcons: Record<string, IconType> = {
  "Morning and evening": MdWbTwilight,
  "Before studying / facing difficulty": MdMenuBook,
  "For parents": MdDiversity1,
  "General supplication": MdVolunteerActivism,
  "Morning and evening (100 times)": MdAllInclusive,
  "Morning and evening (3 times)": MdFilter3,
  "After drinking milk": MdLocalDrink,
  "After eating": MdRestaurant,
  "After eating (alternative)": MdDining,
  "After rainfall": MdWaterDrop,
  "After tashahhud before salam": MdAccountBalance,
  "Before eating": MdSetMeal,
  "Before sleep": MdBed,
  "Before sleep (alternative)": MdSingleBed,
  "Before studying / seeking knowledge": MdMenuBook,
  "Before travel": MdFlightTakeoff,
  "Before travel / boarding transport": MdDirectionsCar,
  "Entering home": MdHome,
  "Entering mosque": MdAccountBalance,
  "Evening remembrance": MdDarkMode,
  "For anxiety and stress": MdHealthAndSafety,
  "For anxiety, stress, and worry": MdSpa,
  "For distress and hardship": MdSentimentDissatisfied,
  "For stress and difficulty": MdSupport,
  "Forgetting to say Bismillah before eating": MdRestaurant,
  "Hearing thunder": MdThunderstorm,
  "Leaving home": MdMeetingRoom,
  "Leaving mosque": MdExitToApp,
  "Morning and evening (Sayyidul Istighfar)": MdCleanHands,
  "Morning remembrance": MdWbSunny,
  "Responding to someone's sneeze": MdHealthAndSafety,
  "Response when sneezer says Alhamdulillah": MdVolunteerActivism,
  "Upon waking up": MdLightMode,
  "Wearing new clothes": MdCheckroom,
  "When it rains": MdWaterDrop,
  "When looking in mirror": MdFace,
  "When sneezing (sneezer says)": MdSick,
};

export function getDuaOccasionIcon(occasion: string) {
  return occasionIcons[occasion] ?? MdAutoStories;
}
